name: Linux container

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        CONTAINER: [
          "almalinux:9.5-20241118",
          "alpine:3.17",
          "alpine:3.17.7",
          "alpine:3.18",
          "alpine:3.18.6",
          "alpine:3.19",
          "alpine:3.19.1",
          "amazonlinux:2023.6.20250203.1",
          "archlinux:base-20250209.0.306557",
          "clearlinux:base",
          "debian:12-slim",
          "debian:unstable-slim",
          "debian:testing-slim",
          "devuan/devuan:daedalus-2024-11-28",
          "fedora:38",
          "fedora:39",
          "fedora:40",
          "fedora:41",
          "opensuse/tumbleweed",
          "oraclelinux:9",
          "rockylinux:9",
          "rockylinux:9.3",
          "ubuntu:22.04",
          "ubuntu:24.04",
          "ubuntu:24.10",
        ]
        CC: [clang, gcc]
        ASM: [asm=no, asm=yes]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - name: Install tar gzip on amazonlinux
      if: startsWith(matrix.CONTAINER, 'amazonlinux:')
      run: dnf install -qy tar gzip

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: misc/install-deps.sh ${{ matrix.CONTAINER }}

    - name: Build libraries
      run: |
        autoreconf -fi
        ./configure --disable-silent-rules --enable-shared --enable-static --enable-${{ matrix.ASM }} CC=${{ matrix.CC }}
        make

    - name: Build examples
      run: make examples

    - name: Run examples
      run: make examples-run

    - name: Examine build artifacts
      run: ls -lh .libs/*.so* && sha256sum .libs/*.so
