matrix:
  platform:
    - linux/amd64
   #- linux/arm64
  ALPINE_VERSION:
   #- 3.18
    - 3.19
  CC:
    - clang
   #- gcc

steps:
 alpine-${ALPINE_VERSION}-${CC}:
   image: alpine:${ALPINE_VERSION}
   commands:
     - export CI=true
     - PATH=$PATH:~/.local/bin
     - export WORKDIR=`pwd`
     - export CC=${CC}
     - ./misc/install-alpine-deps.sh
     - mkdir dist
     - CC=$CC make
     - CC=$CC make install
     - CC=$CC make examples
     - CC=$CC make examples-run
     - ls -alh dist/*.so
     - sha256sum dist/*.so

