name: Debian

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang", "gcc"]
        ASM: ["yes", "no"]
        CONTAINER: ["debian:testing-slim"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Debian testing deps
      run: |
        ./misc/install-debian-testing-deps.sh
        apt install -y --no-install-recommends autoconf automake libtool

    - name: Build
      run: |
        autoreconf -fi
        CC=${{ matrix.CC }} CFLAGS="-fno-lto" ./configure --prefix=/usr/local --enable-asm=${{ matrix.ASM }} && make

    - name: Test install
      run: sudo make install

    - name: Register libraries
      run: sudo ldconfig /usr/local/lib

    - name: Build examples
      run: make examples

    - name: Run examples
      run: make examples-run

    - name: Examine build artifacts
      run: ls -alh .libs/*.so && sha256sum .libs/*.so
