name: Alpine

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang", "gcc"]
        ASM: ["yes", "no"]
        CONTAINER: ["alpine:3.19.1", "alpine:3.19", "alpine:3.18.6",
                    "alpine:3.18", "alpine:3.17.7", "alpine:3.17"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Install alpine deps
      run: ./misc/install-alpine-deps.sh

    - name: Build
      run: CC=${{ matrix.CC }} CFLAGS="-fno-lto" ./configure --prefix="$HOME/inst" --enable-asm=${{ matrix.ASM }} && make

    - name: Test install
      run: make install

    - name: Build examples
      run: make examples

    - name: Run examples
      run: make examples-run

    - name: Examine build artifacts
      run: ls -alh .libs/*.so && sha256sum .libs/*.so
