name: Alpine multi-arch docker build and test (clang)
on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  multiarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang"]
        ASM: ["asm=no"]
        CONTAINER: ["alpine"]
        DOCKER_ARCH_ARGS: [
                      "--platform linux/arm/v6 arm32v6/alpine",
                      "--platform linux/arm/v7 arm32v7/alpine",
                      "--platform linux/i386 i386/alpine",
                      "--platform linux/arm64/v8 arm64v8/alpine",
                      "--platform linux/amd64 amd64/alpine",
                      "--platform linux/riscv64 riscv64/alpine:edge",
                      "--platform linux/ppc64le ppc64le/alpine",
                      "--platform linux/s390x s390x/alpine",
        ]
      fail-fast: false
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: checkout
      uses: actions/checkout@v4

    - name: Install requirements
      run : sudo apt update && sudo apt install -y --no-install-recommends autoconf automake libtool

    - name: check kernel
      run: |
        mount | grep binfmt_misc
        docker info
        uname -a

    - name: Run in Docker
      run: |
        docker run \
          -v $(pwd):/${{ github.workspace }} \
          -w ${{ github.workspace }} \
          -e "CC=${{ matrix.CC }}" \
          -e "CFLAGS=-fno-lto" \
          --rm \
          ${{ matrix.DOCKER_ARCH_ARGS}} \
          /bin/sh \
          -c "misc/install-deps.sh alpine && ./misc/docker-gha-fixup.sh && autoreconf -fi && ./configure --disable-silent-rules --enable-${{ matrix.ASM }} && make install examples-run test-python && ls -alh .libs/*.so* && sha256sum .libs/*.so"
