name: Clear Linux

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        CC: ["clang", "gcc"]
        ASM: ["asm=no", "asm=yes"]
        CONTAINER: ["clearlinux:latest"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Gather Clear Linux version info
      run: swupd info

    - name: Install Clear Linux deps
      run: ./misc/install-clearlinux-deps.sh

    - name: Build
      run: |
        autoreconf -fi
        ./configure --prefix=/usr/local --disable-silent-rules --enable-shared --enable-${{ matrix.ASM }} CC=${{ matrix.CC }}
        make

    - name: Test install
      run: sudo make install

    - name: Register libraries
      run: sudo ldconfig /usr/local/lib

    - name: Build examples
      run: make examples

    - name: Run examples
      run: make examples-run

    - name: Examine build artifacts
      run: ls -alh .libs/*.so* && sha256sum .libs/*.so
