name: Alpine address sanitizer

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CC: clang

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ASM: ["asm=yes", "asm=no"]
        CONTAINER: ["alpine:3.19.1", "alpine:3.19", "alpine:3.18.6",
                    "alpine:3.18", "alpine:3.17.7", "alpine:3.17"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Install alpine deps
      run: ./misc/install-alpine-deps.sh

    - name: Build and install library
      env:
        CFLAGS: -fsanitize=address
      run: |
        autoreconf -fi
        ./configure --prefix="${HOME}/inst" --disable-silent-rules --disable-shared --enable-static --enable-${{ matrix.ASM }} --enable-debug
        make install
        echo PKG_CONFIG_PATH="${HOME}/inst/lib/pkgconfig" >> $GITHUB_ENV

    - name: CGO_LDFLAGS for 8MB stack
      if: endsWith(matrix.ASM, '=no')
      run: echo CGO_LDFLAGS=-Wl,-z,stack-size=0x800000 >> $GITHUB_ENV

    - name: Show go env
      run: go env

    - name: Build and test 511 with asan
      run: cd src/ctidh511 && go test -v -o asan-test -timeout 0 -asan ./...

    - name: Build and test 512 with asan
      run: cd src/ctidh512 && go test -v -o asan-test -timeout 0 -asan ./...

    - name: Build and test 1024 with asan
      run: cd src/ctidh1024 && go test -v -o asan-test -timeout 0 -asan ./...

    - name: Build and test 2048 with asan
      run: cd src/ctidh2048 && go test -v -o asan-test -timeout 0 -asan ./...
