name: Ubuntu address sanitizer

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CC: clang

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ASM: ["yes", "no"]
        CONTAINER: ["ubuntu:23.10", "ubuntu:24.04"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu miminal golang deps
      run: |
        ./misc/install-debian-deps-go-sanitizer.sh
        apt install -y --no-install-recommends autoconf automake libtool pkg-config
        echo "PKG_CONFIG_PATH=${HOME}/inst/lib/pkgconfig" >> $GITHUB_ENV

    - name: Build and install C library with asan
      env:
        CFLAGS: -fsanitize=address -fno-omit-frame-pointer -g3 -fno-lto
      run: |
        autoreconf -fi
        ./configure --prefix="${HOME}/inst" --disable-shared --enable-static --enable-asm=${{ matrix.ASM }} && make install

    - name: Show go env
      run: go env

    - name: Build and test with asan
      run: cd src/ctidh1024 && go test -timeout 0 -asan -v ./...
