name: Ubuntu address sanitizer

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CGO_CFLAGS: -fsanitize=address -fpie -fPIC -fPIE -fno-omit-frame-pointer -g3 -fno-lto

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang"]
        PORTABLE: ["0", "1"]
        CONTAINER: ["ubuntu:22.04", "ubuntu:23.10", "ubuntu:24.04"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu deps
      run: ./misc/install-debian-deps.sh

    - name: Show go env
      run: go env

    - name: Build and test with asan
      run: CC=${{ matrix.CC }} HIGHCTIDH_PORTABLE=${{ matrix.PORTABLE }} cd src/ctidh1024 && go test -timeout 0 -asan -v ./...
