name: Alpine multi-arch docker build and test (clang)
on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  multiarch:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        PLATFORM: [
          "linux/amd64 amd64/alpine",
          "linux/arm/v6 arm32v6/alpine",
          "linux/arm/v7 arm32v7/alpine",
          "linux/arm64/v8 arm64v8/alpine",
          "linux/i386 i386/alpine",
          "linux/riscv64 riscv64/alpine:edge",
          "linux/ppc64le ppc64le/alpine",
          "linux/s390x s390x/alpine",
        ]
      fail-fast: false
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: checkout
      uses: actions/checkout@v4

    - name: Install requirements
      run: misc/install-deps.sh ubuntu

    - name: Run autoreconf
      run: autoreconf -fi

    - name: check kernel
      run: |
        mount | grep binfmt_misc
        docker info
        uname -a

    - name: Run in Docker
      run: |
        docker run \
          -v $(pwd):/${{ github.workspace }} \
          -w ${{ github.workspace }} \
          -e CC=clang \
          --rm \
          --platform ${{ matrix.PLATFORM }} \
          /bin/sh \
          -c "misc/install-deps.sh alpine --python && ./configure --disable-silent-rules --disable-static && make examples-run test-python && ls -lh .libs/*.so* && sha256sum .libs/*.so"
