name: Alpine address sanitizer

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CGO_CFLAGS: -fsanitize=address -fpie -fPIC -fPIE -fno-omit-frame-pointer -g3 -fno-lto 
  CC: clang

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PORTABLE: ["0", "1"]
        CONTAINER: ["alpine:3.19.1", "alpine:3.19", "alpine:3.18.6",
                    "alpine:3.18", "alpine:3.17.7", "alpine:3.17"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Install alpine deps
      run: ./misc/install-alpine-deps.sh

    - name: Show go env
      run: go env

    - name: Build and test with asan
      run: HIGHCTIDH_PORTABLE=${{ matrix.PORTABLE }} cd src/ctidh1024 && go test -timeout 0 -asan -v ./...
