name: Almalinux

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang", "gcc"]
        ASM: ["yes", "no"]
        CONTAINER: ["almalinux:latest"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Almalinux deps
      run: |
        ./misc/install-alma-deps.sh
        dnf install -y autoconf automake libtool

    - name: Build C library
      run: |
        autoreconf -fi
        CC=${{ matrix.CC }} CFLAGS="-fno-lto" ./configure --enable-asm=${{ matrix.ASM }}
        make
    - name: Test install
      run: make install

    - name: Register libraries
      run: sudo ldconfig /usr/local/lib

    - name: Build examples
      run: make examples

    - name: Run examples
      run: make examples-run

    - name: Examine build artifacts
      run: ls -alh dist/*.so && sha256sum dist/*.so
