name: Archlinux

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang", "gcc"]
        ASM: ["asm=yes", "asm=no"]
        CONTAINER: ["archlinux:latest"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Arch deps
      run: ./misc/install-arch-deps.sh

    - name: Build
      run: |
        autoreconf -fi
        ./configure --prefix=/usr/local --disable-silent-rules --enable-shared --enable-${{ matrix.ASM }} CC=${{ matrix.CC }} CFLAGS="-fno-lto" && make

    - name: Test install
      run: sudo make install

    - name: Register libraries
      run: sudo ldconfig /usr/local/lib

    - name: Build examples
      run: make examples

    - name: Run examples
      run: make examples-run

    - name: Examine build artifacts
      run: ls -alh .libs/*.so && sha256sum .libs/*.so
