name: Alpine address sanitizer

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CC: clang

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ASM: ["asm=yes", "asm=no"]
        CONTAINER: ["alpine:3.19.1", "alpine:3.19", "alpine:3.18.6",
                    "alpine:3.18", "alpine:3.17.7", "alpine:3.17"]
      fail-fast: false
    container: ${{ matrix.CONTAINER }}
    steps:
    - uses: actions/checkout@v4

    - name: Install alpine deps
      run: |
        ./misc/install-alpine-deps.sh
        echo "PKG_CONFIG_PATH=${HOME}/inst/lib/pkgconfig" >> $GITHUB_ENV

    - name: Build and install C library with asan and large stack
      if: ${{ matrix.ASM == 'asm=no' }}
      env:
        CFLAGS: -fsanitize=address -fno-omit-frame-pointer -g3 -fno-lto
        LDFLAGS: -Wl,-z,stack-size=0x1F40000
      run: |
        autoreconf -fi
        ./configure --prefix="${HOME}/inst" --disable-silent-rules --disable-shared --enable-static --enable-${{ matrix.ASM }} && make install

    - name: Build and install C library with asan and default stack
      if: ${{ matrix.ASM == 'asm=yes' }}
      env:
        CFLAGS: -fsanitize=address -fno-omit-frame-pointer -g3 -fno-lto
      run: |
        autoreconf -fi
        ./configure --prefix="${HOME}/inst" --disable-shared --enable-static --enable-${{ matrix.ASM }} && make install

    - name: Show go env
      run: go env

    - name: Build and test 511 with asan
      run: cd src/ctidh511 && go test -o asan-test -timeout 0 -asan -v ./...

    - name: Build and test 512 with asan
      run: cd src/ctidh512 && go test -o asan-test -timeout 0 -asan -v ./...

    - name: Build and test 1024 with asan
      run: cd src/ctidh1024 && go test -o asan-test -timeout 0 -asan -v ./...

    - name: Build and test 2048 with asan
      run: cd src/ctidh2048 && go test -o asan-test -timeout 0 -asan -v ./...
