name: FreeBSD fiat build with clang (non-GNU make)

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    name: FreeBSD clang build of fiat backend (non-GNU make)
    env:
      LANG: "C"
      CC: "clang"
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: misc/install-deps.sh ubuntu

    - name: Run autoreconf
      run: autoreconf -fi

    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        release: "14.0"
        envs: 'LANG CC'
        usesh: true
        prepare: |
          uname -a
          freebsd-version
          pkg install -y llvm-13
          clang -v
          echo $SHELL
        run: ./configure --disable-silent-rules && make
