name: FreeBSD fiat build with clang

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: FreeBSD clang build of fiat backend
    env:
      CC: "clang"
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        release: "14.0"
        envs: 'LANG LD CC MAKE HIGHCTIDH_PORTABLE'
        usesh: true
        prepare: |
          uname -a
          freebsd-version
          pkg install -y llvm-13
          pkg install -y bash
          pkg install -y autoconf
          pkg install -y automake
          pkg install -y libtool
          clang -v
          echo $SHELL

        run: |
          autoreconf -fi
          ./configure
          make test-quick
