name: MacOS Golang build and test

on: [push]

env:
  CC: clang

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["macos-14"]
        go-version: [ "1.20.x", "1.21.x", "1.22.7", "1.23.x"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install tools
        run: |
          brew install make autoconf automake libtool pkg-config
          echo PKG_CONFIG_PATH="${HOME}/inst/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build and install C library
        shell: bash
        run: autoreconf -fi && ./configure --prefix="${HOME}/inst" --disable-silent-rules --disable-shared --enable-static && make install

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        shell: bash
        run: go version

      - name: Install golang dependencies
        shell: bash
        run: go get -v ./src/ctidh511

      - name: Build golang
        shell: bash
        run: |
          go build -v ./...

      - name: Golang test
        shell: bash
        run: |
          go test -v ./src/ctidh511
          go test -v ./src/ctidh512
          go test -v ./src/ctidh1024
          go test -v ./src/ctidh2048
