name: MacOS Python build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        OS: ["macos-14"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install tools
      run: brew install make autoconf automake libtool

    - name: Gather runtime environment
      shell: bash
      run: |
       python -V
       bash --version

    - name: Build and install C library
      shell: bash
      run: |
        autoreconf -fi
        ./configure --prefix="${HOME}/inst"
        make install

    - name: Install Python dependencies
      shell: bash
      run: python -m pip install --upgrade build pip setuptools wheel pytest pytest-xdist

    - name: Build wheel
      shell: bash
      run: |
        cd src && python -m build
        pip install --force-reinstall dist/highctidh-*.whl

    - name: Test with pytest
      shell: bash
      run: |
        export DYLD_LIBRARY_PATH="${HOME}/inst/lib"
        python -c 'from highctidh import bench; bench.simple_bench()'
        py.test -v
