name: NetBSD fiat build with gcc

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: NetBSD gcc build of fiat backend
    env:
      CC: "gcc"
    steps:
    - uses: actions/checkout@v4
    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        release: "10.0"
        envs: 'CC'
        usesh: true
        prepare: |
          uname -a
          /usr/sbin/pkg_add gcc10
          gcc -v
          make -v
          /usr/sbin/pkg_add autoconf
          /usr/sbin/pkg_add automake
          /usr/sbin/pkg_add libtool

        run: |
          autoreconf -fi
          ./configure
          make test-quick
