name: NetBSD fiat build with gcc

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: NetBSD gcc build of fiat backend
    env:
      LANG: "C"
      CC: "gcc"
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: misc/install-deps.sh ubuntu

    - name: Run autoreconf
      run: autoreconf -fi

    - name: Build and test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        release: "10.0"
        envs: 'LANG CC'
        usesh: true
        prepare: |
          uname -a
          /usr/sbin/pkg_add gcc10
          gcc -v
        run: ./configure --disable-silent-rules && make test-quick
