name: Nix

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      #- uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix flake check
