name: Omnios fiat build with gcc

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Omnios gcc build of fiat backend
    env:
      LANG: "C"
      CC: "gcc"
    steps:
    - uses: actions/checkout@v4
    - name: Build and test in Omnios
      id: test
      uses: vmactions/omnios-vm@v1
      with:
        release: "r151046"
        envs: 'LANG CC'
        usesh: true
        prepare: |
          uname -a
          psrinfo -vp
          cat /etc/release
          pkg install developer/object-file developer/linker system/header system/library/math shell/bash developer/gcc12
          pkg install developer/build/autoconf developer/build/automake developer/build/libtool
          gcc -v

        run: |
          autoreconf -fi
          ./configure --disable-silent-rules
          make test-quick
