name: Omnios fiat build with gcc

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Omnios gcc build of fiat backend
    env:
      LANG: "C"
      CC: "gcc"
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: misc/install-deps.sh ubuntu

    - name: Run autoreconf
      run: autoreconf -fi

    - name: Build and test in Omnios
      id: test
      uses: vmactions/omnios-vm@v1
      with:
        release: "r151046"
        envs: 'LANG CC'
        usesh: true
        prepare: |
          uname -a
          psrinfo -vp
          cat /etc/release
          pkg install developer/object-file developer/linker system/header system/library/math developer/gcc12
          gcc -v
        run: ./configure --disable-silent-rules && make test-quick
