name: OpenBSD fiat build with clang 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OpenBSD clang build of fiat backend
    env:
      CC: "clang"
    steps:
    - uses: actions/checkout@v4
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@v1
      with:
        release: "7.5"
        envs: 'CC'
        usesh: true
        prepare: |
          uname -a
          pkg_add bash
          make -v
          clang -v
          echo $SHELL

        run: |
          ./configure
          make test-quick
