name: Solaris 11.4 i86pc build with gcc

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ASM: [asm=no, asm=yes]
    env:
      LANG: "C"
      CC: "gcc"
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: misc/install-deps.sh ubuntu

    - name: Run autoreconf
      run: autoreconf -fi

    - name: Build and test in Solaris
      id: test
      uses: vmactions/solaris-vm@v1
      with:
        release: "11.4-gcc"
        envs: 'LANG CC'
        usesh: true
        prepare: |
          uname -a
          isainfo -v
          pkgutil -U
        run: ./configure --disable-silent-rules --enable-${{ matrix.ASM }} && make test-quick
