name: Solaris 11.4 asm i86pc build with gcc

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Solaris i86pc gcc build of asm backend
    env:
      CC: "gcc"
    steps:
    - uses: actions/checkout@v4
    - name: Test in Solaris
      id: test
      uses: vmactions/solaris-vm@v1
      with:
        release: "11.4-gcc"
        envs: 'CC'
        usesh: true
        prepare: |
          uname -a
          isainfo -v
          pkgutil -U

        run: |
          ./configure --enable-asm=yes
          make test-quick
