name: Solaris 11.4 i86pc build with gcc

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ASM: ["yes", "no"]
    env:
      CC: "gcc"
    steps:
    - uses: actions/checkout@v4
    - name: Test in Solaris
      id: test
      uses: vmactions/solaris-vm@v1
      with:
        release: "11.4-gcc"
        envs: 'CC'
        usesh: true
        prepare: |
          uname -a
          isainfo -v
          pkgutil -U
          pkg install autoconf automake libtool

        run: |
          autoreconf -fi
          ./configure --enable-asm=${{ matrix.ASM }}
          make test-quick
