name: Build Debian GNU/Linux Python package and run pytest

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        CC: ["clang", "gcc"]
        ASM: ["asm=yes", "asm=no"]
    steps:
    - uses: actions/checkout@v4

    - name: Install Python deps for testing
      run: sudo bash -c ./misc/install-debian-deps.sh

    - name: Build and install C library
      run: |
        autoreconf -fi
        ./configure --prefix="${HOME}/inst" --disable-silent-rules --enable-shared --enable-${{ matrix.ASM }} CC=${{ matrix.CC }}
        make install
        echo LD_LIBRARY_PATH="${HOME}/inst/lib" >> $GITHUB_ENV

    - name: Build Debian package
      run: make deb

    - name: Install Debian package
      run: sudo dpkg -i dist/python3-highctidh_*.deb

    - name: List Debian package contents
      run: dpkg -L python3-highctidh

    - name: Run pytest
      run: make pytest

    - name: Print hashes
      run: sha256sum dist/*.deb && ls -alh dist/*.deb
