name: Ubuntu WebAssembly build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install cross compiler deps
      run: sudo ./misc/install-ubuntu-webassembly-deps.sh

    - name: Display compiler version
      run: ${{ matrix.CC }} -v

    - name: Build 
      run: ./configure && make wasm
