name: Go cross compile

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ARCH: [
          amd64,
          amd64v3,
          arm32v5,
          arm32v6,
          arm32v7,
          arm64,
          i386,
          mips64,
          mips64le,
          mips,
          mipsle,
          ppc64,
          ppc64le,
          riscv64,
          s390x,
        ]
        go-version: ["1.19", "1.20", "1.21.x", "1.22"]
        include:
          - go-version: "1.22"
            ARCH: arm32v5,hardfloat
          - go-version: "1.22"
            ARCH: arm32v6,softfloat
          - go-version: "1.22"
            ARCH: arm32v7,softfloat
#          - go-version: "1.23"
#            ARCH: arm64v9
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Run autoreconf
      run: autoreconf -fi

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Display Go version
      run: go version

    - name: Install Golang deps
      run: sudo ./misc/install-debian-go-deps-by-arch.sh ${{ matrix.ARCH }}

    - name: Build Golang cgo
      run: ./misc/test-golang-cross.sh ${{ matrix.ARCH }}
