name: Ubuntu WebAssembly build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install cross compiler deps
      run: sudo ./misc/install-ubuntu-webassembly-deps.sh

    - name: Display compiler version
      run: emcc -v

    - name: Build
      run: autoreconf -fi && emconfigure ./configure --disable-silent-rules && make -j $(nproc) wasm
