name: Ubuntu WebAssembly build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install cross compiler deps
      run: |
        sudo ./misc/install-ubuntu-webassembly-deps.sh
        sudo apt install -y --no-install-recommends autoconf automake libtool

    - name: Display compiler version
      run: emcc -v

    - name: Build
      run: autoreconf -fi && emconfigure ./configure --disable-shared --enable-static && make wasm
