name: Build Debian GNU/Linux Python binding package and run pytest

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang", "gcc"]
        ASM: ["yes", "no"]
    steps:
    - uses: actions/checkout@v4

    - name: Install Python deps for testing
      run: sudo bash -c "./misc/install-debian-deps.sh && apt install -y --no-install-recommends autoconf automake libtool"

    - name: Build and install C library
      run: |
        autoreconf -fi
        ./configure --prefix="${HOME}/inst" --enable-asm=${{ matrix.ASM }} CC=${{ matrix.CC }} CFLAGS="-fno-lto"
        make install
        echo "LD_LIBRARY_PATH=${HOME}/inst/lib" >> $GITHUB_ENV

    - name: Build Debian package
      run: make deb

    - name: Install Debian package
      run: sudo dpkg -i dist/python3-highctidh_*.deb

    - name: List Debian package contents
      run: dpkg -L python3-highctidh

    - name: Run pytest
      run: make pytest

    - name: Print hashes
      run: sha256sum dist/*.deb && ls -alh dist/*.deb
