name: Build Debian GNU/Linux Python binding package and run pytest

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang", "gcc"]
        ASM: ["yes", "no"]
    steps:
    - uses: actions/checkout@v4

    - name: Install Python deps for testing
      run: sudo bash -c ./misc/install-debian-deps.sh

    - name: Build and install C library
      run: |
        CC=${{ matrix.CC }} CFLAGS="-fno-lto" ./configure --prefix="${HOME}/inst" --enable-asm=${{ matrix.ASM }}
        make install

    - name: Build Debian package
      run: make deb

    - name: Install Debian package
      run: sudo dpkg -i dist/python3-highctidh_*.deb

    - name: List Debian package contents
      run: dpkg -L python3-highctidh

    - name: Run pytest
      run: LD_LIBRARY_PATH="${HOME}/inst/lib" make pytest

    - name: Print hashes
      run: sha256sum dist/*.deb && ls -alh dist/*.deb
