name: Ubuntu C library cross compile

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        CC: ["clang", "gcc"]
    steps:
    - uses: actions/checkout@v4

    - name: Install cross compiler deps
      run: sudo ./misc/install-ubuntu-latest-cross-deps.sh

    - name: Display compiler version
      run: ${{ matrix.CC }} -v

    - name: Build 
      run: |
        autoreconf -fi
        ./configure --prefix=/usr/local --disable-silent-rules --enable-shared CC=${{ matrix.CC }}
        make

    - name: Install
      run: sudo make install && sudo ldconfig

    - name: Build C library examples
      run: make examples

    - name: Run C library examples
      run: make examples-run
