name: Ubuntu C library cross compile

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        CC: ["clang", "gcc"]
    steps:
    - uses: actions/checkout@v4

    - name: Install cross compiler deps
      run: misc/install-deps.sh x-ubuntu-24.04-cross

    - name: Display compiler version
      run: ${{ matrix.CC }} -v

    - name: Build with cross compiler
      run: misc/test-c-lib-cross-${{ matrix.CC }}.sh
