name: Build Ubuntu GNU/Linux package and run pytest

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        CC: ["clang-14", "gcc"]
        PORTABLE: ["0", "1"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Install Python deps for testing
      run: sudo bash -c ./misc/install-ubuntu-deps.sh

    - name: Build Debian package with assembler backend
      run: CC=${{ matrix.CC }} CFLAGS="-fno-lto" HIGHCTIDH_PORTABLE=${{ matrix.PORTABLE }} make deb

    - name: Install Debian package
      run: sudo dpkg -i dist/python3-highctidh_*.deb

    - name: List Debian package contents
      run: dpkg -L python3-highctidh

    - name: Run pytest
      run: make pytest

    - name: Print hashes
      run: sha256sum dist/*.deb && ls -alh dist/*.deb
