name: Ubuntu C library cross compile

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang", "gcc"]
    steps:
    - uses: actions/checkout@v4

    - name: Display compiler version
      run: ${{ matrix.CC }} -v

    - name: Install cross compiler deps
      run: sudo ./misc/install-ubuntu-latest-cross-deps.sh

    - name: Run autoreconf
      run: autoreconf -fi

    - name: Build with cross compiler
      run: misc/test-c-lib-cross-${{ matrix.CC }}.sh
