name: Windows Msys2 64bit (msvcrt) clang Python pip build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        OS: ["windows-2022"]
        CC: ["clang"]
        ENVIRONMENT: ["MINGW64"] # https://www.msys2.org/docs/environments/
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.ENVIRONMENT }}
        install: >-
          python
          python-pip
          python-build
          python-setuptools
          python-wheel
          python-pytest
          git
          clang
          mingw-w64-clang-x86_64-python-pytest-xdist
          mingw-w64-clang-x86_64-python-flit
          mingw-w64-clang-x86_64-python-distutils-extra
          mingw-w64-x86_64-clang
          make
          autoconf
          automake
          libtool

    - name: Gather runtime environment
      shell: msys2 {0}
      run: |
       echo ${{ matrix.ENVIRONMENT }}
       uname -a
       python -V
       bash --version
       ${{ matrix.CC }} -v

    - name: Build and install C library
      shell: msys2 {0}
      run: |
        autoreconf -fi
        CC=${{ matrix.CC }} ./configure --prefix="$HOME/inst"
        make install

    - name: Build highctidh
      shell: msys2 {0}
      run: |
        export SETUPTOOLS_USE_DISTUTILS=local
        export SOURCE_DATE_EPOCH=`git log -1 --pretty=%ct`
        OPT="" pip install -v --break-system-packages -e src/

    - name: Test with pytest
      shell: msys2 {0}
      run: |
        export LD_LIBRARY_PATH="$HOME/inst/lib"
        python -c 'from highctidh import bench; bench.simple_bench()'
        pytest -v
