name: Windows fiat build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        OS: ["windows-2022", "windows-2019"]
        CC: ["clang"]
      fail-fast: false
    runs-on: ${{ matrix.OS }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.ENVIRONMENT }}
        install: >-
          make
          autoconf
          automake
          libtool

    - name: Gather toolchain info
      shell: bash
      run: |
        make -v
        ${{ matrix.CC }} -v

    - name: compile and test-quick
      shell: bash
      run: autoreconf -fi && ./configure && make test-quick
