name: Windows fiat build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        OS: ["windows-2022", "windows-2019"]
        CC: ["clang"]
      fail-fast: false
    runs-on: ${{ matrix.OS }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        install: >-
          make
          autotools
          libtool

    - name: Gather toolchain info
      shell: msys2 {0}
      run: |
        make -v
        ${{ matrix.CC }} -v

    - name: compile and test-quick
      shell: msys2 {0}
      run: |
        autoreconf -fi
        ./configure --disable-silent-rules
        make test-quick
